services:
  - type: web
    name: analiza-sentiment
    env: python
    buildCommand: |-
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python -m nltk.downloader vader_lexicon stopwords
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
    plan: free
